# Generated by Django 4.2 on 2023-04-08 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('distance', models.IntegerField(default=None)),
                ('milage', models.IntegerField(default=None)),
                ('electricity_consumption', models.IntegerField(default=None)),
                ('gass_volume', models.IntegerField(default=None)),
                ('emission_factor', models.IntegerField(default=None)),
                ('carbon_footprint', models.IntegerField(default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
